// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MUX94lM010APvNgBejJhwlsOBCIOOyM',
    appId: '1:980416258500:web:e7aaa9da1600d4a7260491',
    messagingSenderId: '980416258500',
    projectId: 'adha-firebase',
    authDomain: 'adha-firebase.firebaseapp.com',
    storageBucket: 'adha-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9gPJZeAMAV5mIv_K2APruQv7JUNz0b0',
    appId: '1:980416258500:android:8b9d2ce7e68ba235260491',
    messagingSenderId: '980416258500',
    projectId: 'adha-firebase',
    storageBucket: 'adha-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvWpzBAzvjz-ebc7kpp7t8ku17vIyf6JY',
    appId: '1:980416258500:ios:825ed8549e5f84a0260491',
    messagingSenderId: '980416258500',
    projectId: 'adha-firebase',
    storageBucket: 'adha-firebase.appspot.com',
    iosBundleId: 'com.example.adhaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvWpzBAzvjz-ebc7kpp7t8ku17vIyf6JY',
    appId: '1:980416258500:ios:484bbf766aa868e7260491',
    messagingSenderId: '980416258500',
    projectId: 'adha-firebase',
    storageBucket: 'adha-firebase.appspot.com',
    iosBundleId: 'com.example.adhaTask.RunnerTests',
  );
}
